export enum UnidadMedida {
  Miligramo = "mg",
  Gramo = "g",
  Kilogramo = "kg",
  Mililitro = "ml",
  Litro = "l",
  Cucharadita = "cucharadita",
  Cucharada = "cucharada",
  Taza = "taza",
  Pizca = "pizca",
  PizcaGenerosa = "pizca generosa",
  TazaCafe = "taza de café",
  TazaTe = "taza de té",
  TazaDesayuno = "taza de desayuno",
  TazaCereales = "taza de cereales",
  TazaPostre = "taza de postre",
  TazaCapacidad = "taza de capacidad",
  TazaCapacidadSopera = "taza de capacidad sopera",
  TazaCapacidadLiquidos = "taza de capacidad líquidos",
  Unidad = "unidad",
  Pieza = "pieza",
  Rodaja = "rodaja",
  Rebanada = "rebanada",
  Hoja = "hoja",
  Ramita = "ramita",
  Diente = "diente",
  Rama = "rama",
  Trozo = "trozo",
  Tira = "tira",
  Pata = "pata",
  Corteza = "corteza",
  Pie = "pie",
  Cabeza = "cabeza",
  Lata = "lata",
  Bolsa = "bolsa",
  Botella = "botella",
  Vaso = "vaso",
  Copa = "copa",
  Cubo = "cubo",
}

export enum CategoriaAlimento {
  Carnes = "Carnes",
  Verduras = "Verduras",
  Lácteos = "Lácteos",
  Cereales = "Cereales",
  Legumbres = "Legumbres",
  Otros = "Otros",
}
